const companiesList = [
    {
        name: "Zzam",
        website: "http://www.zzam.be/fr/",
        phone: "+32.(0)4 226 55 85",
        email: "info@zzam.be",
        street: "Rue de la chaîne 75",
        zip: 4000,
        city: "Liège",
        works: "E-commerces, corporates",
        techs: "Joomla!, Virtuemart",
        notes: ""
    },
    {
        name: "DAPIWEB",
        website: "https://www.dapiweb.com/",
        phone: "+32 498 59 55 08",
        email: "david.rubens@dapiweb.com",
        street: "Rue de l'Armistice 48",
        zip: 4020,
        city: "Liège",
        works: "Vcards, Vitrines, E-commerces",
        techs: "",
        notes: ""
    },
    {
        name: "Noomia",
        website: "https://noomia.be/",
        phone: "+32 (0) 4 254 70 54",
        email: "info@noomia.be",
        street: "Rue Ernest Solvay 29a",
        zip: 4000,
        city: "Liège",
        works: "corporate, Vitrines, E-commerces",
        techs: "Wordpress seulement",
        notes: ""
    },
    {
        name: "Eyaka",
        website: "https://eyaka.be/",
        phone: "04 242 90 45",
        email: "info@eyaka.be",
        street: "Quai Mativa 23",
        zip: 4020,
        city: "Liège",
        works: "réseaux sociaux, vitrines, E-commerces, référencement, audit, web app",
        techs: "Wordpress, Prestashop, Drupal, Podio, Jira, jQuery, MySQL",
        notes: "Ne recherchent pas de stagiaires pour l'instant"
    },
    {
        name: "Contraste Digital / Defimedia",
        website: "https://www.contraste-digital.com/",
        phone: "+32 (0)4 242 47 50",
        email: "",
        street: "Rue de Mulhouse 36",
        zip: 4020,
        city: "Liège",
        works: "réseaux sociaux, vitrines, E-commerces, web app",
        techs: "Android native, Drupal, PHP, Java, Go, Maps System, Python, Scala, Apache Solr, .NET, MongoDB, Talend, AWS, Azure, iOS native, Acquia, Hotjar, Drupal, Angular, Spring, Varnish, Elastic, MySQL, Cassandra, Hadoop, Office 365, PortgreSQL, Wordpress, jQuery",
        notes: "À contacter via formulaire sur leur site"
    },
    {
        name: "Webissimus",
        website: "https://www.webissimus.com/",
        phone: "",
        email: "info@webissimus.com",
        street: "Rue du Vertbois 11",
        zip: 4000,
        city: "Liège",
        works: "corpo, vitrines, E-commerces, référencement, réseaux sociaux, emailing",
        techs: "",
        notes: ""
    },
    {
        name: "Gigaweb",
        website: "http://design.gigaweb.be/",
        phone: "+32(0)10 40 02 18",
        email: "info@gigaweb.be",
        street: "Place des Guillemins 2",
        zip: 4000,
        city: "Liège",
        works: "corpo, vitrines, e-commerces",
        techs: "",
        notes: "Siège social à Ottignies"
    },
    {
        name: "Webadev",
        website: "https://www.webadev.com/fr/",
        phone: "+32 (0)4 229 36 02",
        email: "info@webadev.com",
        street: "Avenue Blonden 23/001",
        zip: 4000,
        city: "Liège",
        works: "corpo, vitrines, CMS, e-commerces, référencement",
        techs: "",
        notes: "Siège social à Ottignies"
    },
    {
        name: "Globule Bleu Liège",
        website: "https://www.globulebleu.com/",
        phone: "+32(0)4.239.84.44",
        email: "start@globulebleu.com",
        street: "Quai Mativa 62",
        zip: 4020,
        city: "Liège",
        works: "corpo, vitrines, CMS, e-commerces, référencement, vidéos (animations), supports visuels (print, flyers, catalogues, affiches), imprimés textiles, identités graphiques",
        techs: "Drupal, Flash, UX/UI, Adobe Creative Suite, HTML5, CSS3, responsive",
        notes: "Aussi à Bruxelles"
    },
    {
        name: "Globule Bleu Bruxelles",
        website: "https://www.globulebleu.com/",
        phone: "+32(0)4.239.84.44",
        email: "start@globulebleu.com",
        street: "Boulevard de l'humanité 237",
        zip: 1620,
        city: "Drogendbos",
        works: "corpo, vitrines, CMS, e-commerces, référencement, vidéos (animations), supports visuels (print, flyers, catalogues, affiches), imprimés textiles, identités graphiques",
        techs: "Drupal, Flash, UX/UI, Adobe Creative Suite, HTML5, CSS3, responsive",
        notes: "Aussi à Liège"
    },
    {
        name: "Synthèse",
        website: "https://www.synthese.be/",
        phone: "+32 4 229 35 56",
        email: "info@synthese.be",
        street: "Rue Pierreuse 29",
        zip: 4000,
        city: "Liège",
        works: "vitrines, corporate, territoires, référencement, identité graphique, rédaction, photo, illustration, supports visuels, vidéo",
        techs: "Wordpress",
        notes: "Mentionne spécifiquement “Stages : Pas pour le web, ni pour la pub”"
    },
    {
        name: "Overshot",
        website: "https://www.overshot.com/",
        phone: "+32 (0)476 58 56 73",
        email: "info@overshot.com",
        street: "Rue du Château Massart 65",
        zip: 4000,
        city: "Liège",
        works: "vitrines, référencement",
        techs: "Wordpress",
        notes: ""
    },
    {
        name: "Miko Digital",
        website: "https://www.mikodigital.com/",
        phone: "04 287 33 24",
        email: "contact@mikodigital.com",
        street: "Rue de la Province 24/36",
        zip: 4020,
        city: "Liège",
        works: "vitrines, corpo, e-commerces, mobile app, référencement, réseaux sociaux, mise en conformité RGPD",
        techs: "Wordpress, React Native (back-end Wordpress), WooCommerce",
        notes: ""
    },
    {
        name: "Bugiweb",
        website: "https://www.bugiweb.com/",
        phone: "+32 04 368 56 00",
        email: "info@bugiweb.com",
        street: "Rue d'Ans 56",
        zip: 4000,
        city: "Liège",
        works: "vitrines, corpo, e-commerces, emailing",
        techs: "CMS maison (Perl/PHP), Perl, mobile app",
        notes: ""
    },
    {
        name: "EPIC Agency",
        website: "https://www.epic.net/en/",
        phone: "+32 78 15 11 45",
        email: "",
        street: "Rue Paradis 62",
        zip: 4000,
        city: "Liège",
        works: "vitrines, corpo, e-commerces, emailing, branding, animations, vidéo",
        techs: "Wordpress, Sketch (ou similaire), Google Tag Manager, Google Analytics",
        notes: "À contacter via formulaire sur leur site"
    },
    {
        name: "Oh! Medias",
        website: "http://ohmedias.com/fr",
        phone: "0476 42 20 53",
        email: "contact@ohmedias.com",
        street: "Avenue du Théatre de Verdure 4",
        zip: 4031,
        city: "Liège",
        works: "one-pagers, vitrines, corpo, mobile app, vidéos, e-commerces, graphismes, supports visuels",
        techs: "CMS maison",
        notes: ""
    },
    {
        name: "Studio Colibri",
        website: "https://www.studiocolibri.be/",
        phone: "",
        email: "bonjour@studiocolibri.be",
        street: "En Féronstrée 104",
        zip: 4000,
        city: "Liège",
        works: "",
        techs: "Statique, pas de DB, CMS maison",
        notes: ""
    },
    {
        name: "In Fine",
        website: "https://infine.net/",
        phone: "+32 4 340 12 60",
        email: "hello@infine.net",
        street: "Quai du Barbou 8a",
        zip: 4020,
        city: "Liège",
        works: "identité visuelle, vitrines, corpo, mobile app, vidéos, e-commerces, graphismes, supports visuels, réseaux sociaux",
        techs: "",
        notes: "Vous pouvez aussi contacter stephanie.mottard@infine.net, responsable des jobs et stages"
    },
    {
        name: "EXIT Studio (Bernard Petithan)",
        website: "https://www.exitstudio.be/",
        phone: "+32 (0)476 38 48 13",
        email: "bernard@petithanb.be",
        street: "Rue de la brasserie 6",
        zip: 4000,
        city: "Liège",
        works: "identité visuelle, vitrines, corpo, mobile app, vidéos, e-commerces, graphismes, supports visuels, réseaux sociaux",
        techs: "Wordpress, Prestashop, Laravel",
        notes: ""
    },
    {
        name: "Infra-Red",
        website: "http://www.infra-red.be/",
        phone: "0032 (0)4 285 71 58",
        email: "info@infra-red.be",
        street: "Rue Belvaux 87",
        zip: 4030,
        city: "Liège",
        works: "identité visuelle, vitrines, corpo, e-commerces, graphismes, supports visuels, packaging",
        techs: "responsive design, Prestashop",
        notes: ""
    },
    {
        name: "Synchrone",
        website: "https://www.synchrone.be/fr/",
        phone: "+32.43440003",
        email: "info@synchrone.be",
        street: "Rue du Fort 5",
        zip: 4671,
        city: "Barchon",
        works: "vitrines, corpo, e-commerces, identités graphiques, supports visuels, photo, emailing, réseaux sociaux, référencement",
        techs: "responsive design, UX/UI, jQuery, Bootstrap, LESS, SASS, Angular.js, Grunt, Gulp, Node",
        notes: ""
    },
    {
        name: "Layout",
        website: "https://www.layout.be/web/",
        phone: "0490 45 52 49",
        email: "web@layout.be",
        street: "Rue Cordemont",
        zip: 4450,
        city: "Juprelle",
        works: "vitrines, corpo, e-commerces, référencement, réseaux sociaux, emailing, graphismes, identités visuelles",
        techs: "",
        notes: ""
    },
    {
        name: "Newave",
        website: "http://www.newave.be/",
        phone: "04 287 09 51",
        email: "floymonjf@gmail.com",
        street: "Rue du parc 50",
        zip: 4432,
        city: "Juprelle",
        works: "e-commerces, vitrines, corpo, référencement, réseaux sociaux",
        techs: "Wordpress, Drupal, Joomla!, Made Simple, Magento, CMS maison, responsive design, WooCommerce, Prestashop, Ogone, Amazone Marketplaces, PayPal, AdWords",
        notes: ""
    },
    {
        name: "Whitecube",
        website: "https://whitecube.be/",
        phone: "+324 287 36 81",
        email: "hello@whitecube.be",
        street: "Rue des Anges 17",
        zip: 4000,
        city: "Liège",
        works: "e-commerces, vitrines, corpo",
        techs: "",
        notes: ""
    },
    {
        name: "Agence Kameleon",
        website: "https://www.agence-kameleon.be/",
        phone: "+32 4 268 26 26",
        email: "info@agence-kameleon.be",
        street: "Square de la Paix 28",
        zip: 4031,
        city: "Liège",
        works: "e-commerces, vitrines, corpo, référencement, animations, emailing, réseaux sociaux",
        techs: "PHP 7, Wordpress, jQuery, MySQL",
        notes: "“Viennent de décider de rediriger la majeure partie de leurs activités d'agence de marketing identitaire vers une autre activité”."
    },
    {
        name: "Jellyfish Creative Studio",
        website: "https://www.jellyfishcreativestudio.be/",
        phone: "+32(0) 474 48 32 31",
        email: "info@jellyfishcreativestudio.be",
        street: "Rue agimont 3",
        zip: 4000,
        city: "Liège",
        works: "graphismes, animations, vidéos, vitrines, e-commerces, corpo, emailing, référencement",
        techs: "responsive design, Drupal, Drupal Commerce, jQuery",
        notes: ""
    },
    {
        name: "Savoir Faire Digital",
        website: "https://www.savoirfaire.digital/fr/",
        phone: "+32 475 701 369",
        email: "hello@savoirfaire.digital",
        street: "Rue sur les Heids 48",
        zip: 4671,
        city: "Barchon",
        works: "graphismes, animations, vidéos, vitrines, e-commerces, corpo, emailing, référencement",
        techs: "e-commerces, vitrines, corpo, référencement, animations",
        notes: ""
    },
    {
        name: "Gambit Financial Solutions Liège",
        website: "https://gambit-finance.com/",
        phone: "+32 4 279 88 00",
        email: "info@gambit-finance.com",
        street: "Rue de Mulhouse 36",
        zip: 4020,
        city: "Liège",
        works: "conseils en investisements, gestion de risque",
        techs: "Angular, Angular.js, .NET",
        notes: "Aussi à Bruxelles, Luxembourg et Paris"
    },
    {
        name: "Gambit Financial Solutions Bruxelles",
        website: "https://gambit-finance.com/",
        phone: "+32 4 279 88 00",
        email: "info@gambit-finance.com",
        street: "Avenue Louise 523",
        zip: 1050,
        city: "Bruxelles",
        works: "conseils en investisements, gestion de risque",
        techs: "Angular, Angular.js, .NET",
        notes: "Aussi à Liège, Luxembourg et Paris"
    },
    {
        name: "Gaming 1",
        website: "https://gaming1.com/",
        phone: "+32 4 228 32 00",
        email: "info@gaming1.com",
        street: "Rue Saint-Exupéry 17",
        zip: 4460,
        city: "Gràce-Hollogne",
        works: "jeux de casinos & paris sportifs (bornes et online)",
        techs: "UX/UI, .NET, Javascript, Testcafe, ISTQB, C#, Dart, HTML Canvas, WebGL, Durandal, KnockoutJS, Aurelia, RequireJS, Lodash",
        notes: ""
    },
    {
        name: "EVS Liège",
        website: "https://evs.com/en",
        phone: "+32 4 361 70 00",
        email: "info@evs.com",
        street: "Rue Bois Saint-Jean 13",
        zip: 4102,
        city: "Seraing",
        works: "broadcast equipment (event broadcasting, analysis, coverage, archiving, gameday entertainment)",
        techs: "UX/UI, C, C++, Java, React, HTML5, CSS3, Javascript, Node.JS, Webservices (REST API), Webpack, Docker, SQL, méthodes agiles (SCRUM), Qt, QML, Python, XML, Shell, Perl, Silverlight, Android, Share Point, MS Office (Word, Excel, Access, Project)",
        notes: "Aussi à Bruxelles, LA (USA), NJ (USA), Australie, Chine, Hong-Kong, France, Italie, Espagne, Mexico, Allemagne, Moyen-Orient et Angleterre"
    },
    {
        name: "EVS Bruxelles",
        website: "https://evs.com/en",
        phone: "",
        email: "info@evs.com",
        street: "Avenue Charles Quint 576",
        zip: 1082,
        city: "Bruxelles",
        works: "broadcast equipment (event broadcasting, analysis, coverage, archiving, gameday entertainment)",
        techs: "UX/UI, C, C++, Java, React, HTML5, CSS3, Javascript, Node.JS, Webservices (REST API), Webpack, Docker, SQL, méthodes agiles (SCRUM), Qt, QML, Python, XML, Shell, Perl, Silverlight, Android, Share Point, MS Office (Word, Excel, Access, Project)",
        notes: "Aussi à Liège, LA (USA), NJ (USA), Australie, Chine, Hong-Kong, France, Italie, Espagne, Mexico, Allemagne, Moyen-Orient et Angleterre"
    },
    {
        name: "Tapptic Liège",
        website: "https://tapptic.com/",
        phone: "+32 4 266 98 55",
        email: "hello@tapptic.com",
        street: "Rue de Mulhouse 36",
        zip: 4020,
        city: "Liège",
        works: "mobile apps, web apps, e-commerces, VR, systèmes embarqués, chatbots",
        techs: "Git, Jira, UX/UI, Swift, Objective-C, HTML5, CSS3, Javascript, React, Angular.js, PHP, Laravel, Symfony2, Node.js, MongoDB, MySQL, CarPlay, Android Auto, Google Home, Amazon Echo, Xamarin, Cordova, XCode, Instruments, Cocoa Pods, Cocoa Touch, AWS Tools, Kotlin",
        notes: "Surtout axés mobiles, donc Swift et Kotlin principalement. Email de contact pour le responsable Liège : michael.carpentier@tapptic.com. Aussi à Bruxelles"
    },
    {
        name: "Tapptic Bruxelles",
        website: "https://tapptic.com/",
        phone: "+32 2 332 45 00",
        email: "hello@tapptic.com",
        street: "Boulevard de la Cambre 28/30",
        zip: 1000,
        city: "Bruxelles",
        works: "mobile apps, web apps, e-commerces, VR, systèmes embarqués, chatbots",
        techs: "Git, Jira, UX/UI, Swift, Objective-C, HTML5, CSS3, Javascript, React, Angular.js, PHP, Laravel, Symfony2, Node.js, MongoDB, MySQL, CarPlay, Android Auto, Google Home, Amazon Echo, Xamarin, Cordova, XCode, Instruments, Cocoa Pods, Cocoa Touch, AWS Tools, Kotlin",
        notes: "Aussi à Liège"
    },
    {
        name: "Produweb Liège",
        website: "https://www.produweb.be/fr/",
        phone: "+32(0)4/344.14.00",
        email: "info@produweb.be",
        street: "Rue de Lantin 149",
        zip: 4000,
        city: "Liège",
        works: "vitrine, corpo, e-commerces, print, référencement, intranet, emailing, réseaux sociaux, app mobiles, vidéos",
        techs: "Magento, Prestashop, responsive design, payements web (Ogone, PayPal, Bancontact, HiPay), CMS maison, Wordpress, Drupal, Google Adwords, Android, iOS",
        notes: "Aussi à Bruxelles et Namur. Formulaire de contact spécifique pour les stages et candidatures spontanées sur leur site"
    },
    {
        name: "Produweb Bruxelles",
        website: "https://www.produweb.be/fr/",
        phone: "+32(0)2/657.38.88",
        email: "info@produweb.be",
        street: "Avenue des Volontaires 19",
        zip: 1160,
        city: "Bruxelles",
        works: "vitrine, corpo, e-commerces, print, référencement, intranet, emailing, réseaux sociaux, app mobiles, vidéos",
        techs: "Magento, Prestashop, responsive design, payements web (Ogone, PayPal, Bancontact, HiPay), CMS maison, Wordpress, Drupal, Google Adwords, Android, iOS",
        notes: "Aussi à Liège et Namur. Formulaire de contact spécifique pour les stages et candidatures spontanées sur leur site"
    },
    {
        name: "Produweb Namur",
        website: "https://www.produweb.be/fr/",
        phone: "",
        email: "info@produweb.be",
        street: "Chaussée de Liège",
        zip: 5100,
        city: "Namur",
        works: "vitrine, corpo, e-commerces, print, référencement, intranet, emailing, réseaux sociaux, app mobiles, vidéos",
        techs: "Magento, Prestashop, responsive design, payements web (Ogone, PayPal, Bancontact, HiPay), CMS maison, Wordpress, Drupal, Google Adwords, Android, iOS",
        notes: "Aussi à Liège et Bruxelles. Formulaire de contact spécifique pour les stages et candidatures spontanées sur leur site"
    },
    {
        name: "Mon Agence Liège",
        website: "https://www.monagence.be/",
        phone: "+32 (0)4 226 76 56",
        email: "",
        street: "Rue de Gomzé 32/05",
        zip: 4140,
        city: "Liège",
        works: "vitrines, corpo, référencement, Marketing digital, accessibilité, e-commerces, CMS",
        techs: "Google AdWords, responsive design, Google Analytics, WooCommerce, Prestashop, Magento",
        notes: "Aussi à Bruxelles. Formulaire de contact sur leur site"
    },
    {
        name: "Mon Agence Bruxelles",
        website: "https://www.monagence.be/",
        phone: "+32 (0)2 627 77 21",
        email: "",
        street: "Avenue Louise 523",
        zip: 1050,
        city: "Bruxelles",
        works: "vitrines, corpo, référencement, Marketing digital, accessibilité, e-commerces, CMS",
        techs: "Google AdWords, responsive design, Google Analytics, WooCommerce, Prestashop, Magento",
        notes: "Aussi à Liège. Formulaire de contact sur leur site"
    },
    {
        name: "E-Mage Concept",
        website: "https://e-mage-concept.be/",
        phone: "+32 (0) 476 74 90 97",
        email: "info@e-mage-concept.be",
        street: "Rouge Thier 18",
        zip: 4920,
        city: "Aywaille",
        works: "vitrines, corpo, e-commerces, identité visuelle, graphismes, print, référencement, emailing, geoloc, analytics, réseaux sociaux",
        techs: "Wordpress, MailChimp, WebSite X5, Adobe Muse, Adobe Photoshop, Adobe inDesign",
        notes: ""
    },
    {
        name: "banG!",
        website: "http://www.bang.be/012/fr/Hello",
        phone: "+32(0)4 384 31 23",
        email: "info@bang.be",
        street: "Rue de la Reffe 19/2",
        zip: 4920,
        city: "Remouchamps",
        works: "CMS, e-commerces, réseaux sociaux, emailing, vidéos, spots pub, packaging, print (papier & textile), lettrage",
        techs: "",
        notes: ""
    },
    {
        name: "Bewive",
        website: "https://www.bewive.be/",
        phone: "0496 64 79 04",
        email: "info@bewive.be",
        street: "Rue de l'alignement 6/1",
        zip: 4032,
        city: "Chênée",
        works: "vitrines, corpo, e-commerces, mobile app, dépannage informatique, référencement, app windows/linux",
        techs: "",
        notes: ""
    },
    {
        name: "StratéTIC",
        website: "https://www.stratetic.com/",
        phone: "+32(0)4 287 03 57",
        email: "salut@stratetic.com",
        street: "Rue Dieusaumé 38",
        zip: 4053,
        city: "Embourg",
        works: "e-commerces, analytics, marketing, stratégie digitale",
        techs: "Prestashop, WooCommerce, Magento, Google Adwords, MailChimp, Wordpress",
        notes: ""
    },
    {
        name: "DJBcom (Bernard Dejosée)",
        website: "https://www.djbcom.be/",
        phone: "+32 496 123 175",
        email: "bernard@dejosee.be",
        street: "Fond Leval 31",
        zip: 4140,
        city: "Sprimont",
        works: "vitrines, e-commerces, impressions tous supports, graphismes (logo)",
        techs: "Wordpress",
        notes: ""
    },
    {
        name: "So Com",
        website: "https://so-com.be/",
        phone: "+32 (0) 4 222 02 00",
        email: "kl@so-com.be",
        street: "Rue du Roua 44",
        zip: 4141,
        city: "Sprimont",
        works: "référencement, e-commerces, vitrines, 3D, vidéo, identité visuelle, print (papier, textiles inclus)",
        techs: "",
        notes: "Formulaire de contact sur leur site"
    },
    {
        name: "Oanna",
        website: "https://www.oanna.be/",
        phone: "+32 (0)85 87 02 70",
        email: "aloha@oanna.be",
        street: "Rue sur Haies 7",
        zip: 4557,
        city: "Tinlot",
        works: "vitrine, corpo, responsive design, logo, identité graphique, prints, lettrages",
        techs: "",
        notes: ""
    },
    {
        name: "Superpink & Ribs",
        website: "https://pinkandribs.com/",
        phone: "",
        email: "infolg@pinkandribs.com",
        street: "Rue du Village 9",
        zip: 4347,
        city: "Fexhe-le-Haut-Clocher",
        works: "vitrine, corpo, pub, e-commerces, graphisme, print, vidéos, emailing, réseaux sociaux",
        techs: "Google Adwords",
        notes: ""
    },
    {
        name: "Ink Studio",
        website: "https://inkstudio.be/",
        phone: "+32 (0)2 543 44 45",
        email: "",
        street: "Rue Fernand Bernier 15",
        zip: 1060,
        city: "Bruxelles",
        works: "branding, logo, graphisme, identité graphique, print, packaging, mobile apps, vitrine, corpo",
        techs: "",
        notes: ""
    },
    {
        name: "HelloMoon",
        website: "https://www.hellomoon.lu/",
        phone: "+32 (0) 496 03 82 99",
        email: "info@hellomoon.lu",
        street: "Grand Rue 80",
        zip: 9711,
        city: "Clervaux",
        works: "e-commerces, vitrines, corpo, immo, photo, référencement, mobile apps, identité graphique, graphisme, emailing",
        techs: "Prestashop, SwiftImmo, Cordova",
        notes: "Adresse valable pour siège social seulement"
    },
    {
        name: "Arkam",
        website: "https://www.arkam.be/",
        phone: "0032 65 84 42 00",
        email: "info@arkam.be",
        street: "Boulevard Initialis 28",
        zip: 7000,
        city: "Mons",
        works: "Analyse de marché, logo, identité graphique, graphisme, photo, packaging, mobile apps, SEO, vitrines, corpo, e-commerces, emailing",
        techs: "",
        notes: ""
    },
    {
        name: "iGLOO",
        website: "https://igloo.be/",
        phone: "+32 10 39 22 28",
        email: "",
        street: "Rue Louis de Geer 6",
        zip: 1348,
        city: "Louvain-La-Neuve",
        works: "project management, perf audit, UX/UI, animations, illustrations, sys admin",
        techs: "Docker, Kubernetes, Node.js, React, Angular, MongoDB, MySQL",
        notes: "Formulaire de contact sur leur site"
    },
    {
        name: "Alinoa Braine-le-Château",
        website: "https://www.alinoa.be/",
        phone: "+32 2 319 08 19",
        email: "jobs@alinoa.be",
        street: "Rue de Tubize 23",
        zip: 1440,
        city: "Braine-le-Château",
        works: "e-commerces, corpo, UX, mobile",
        techs: "Wordpress, WooCommerce",
        notes: "Aussi à Bruxelles"
    },
    {
        name: "Alinoa Bruxelles",
        website: "https://www.alinoa.be/",
        phone: "+32 2 319 08 19",
        email: "jobs@alinoa.be",
        street: "Rue de Broyer 10",
        zip: 1180,
        city: "Uccle",
        works: "e-commerces, corpo, UX, mobile",
        techs: "Wordpress, WooCommerce",
        notes: "Aussi à Braine-le-Château"
    },
    {
        name: "Inside Web",
        website: "https://www.insideweb.be/",
        phone: "+32 474 20 36 37",
        email: "mike@insideweb.be",
        street: "Chaussée de Louvain 435",
        zip: 1380,
        city: "Lasne",
        works: "e-commerces, corpo, vitrines, emailing, sécurité web",
        techs: "Wordpress, Prestashop, Symfony",
        notes: ""
    },
    {
        name: "Paf! Design",
        website: "http://www.pafdesign.be/",
        phone: "+32(0)2 743 47 28",
        email: "jobs@pafdesign.be",
        street: "Avenue des Volontaires 19",
        zip: 1160,
        city: "Bruxelles",
        works: "e-commerces, corpo, vitrines, emailing",
        techs: "Wordpress, PHP",
        notes: "Pour un stage, envoyer portfolio et candidature à l'email mentionné"
    },
    {
        name: "Prospect",
        website: "https://prospect.io/",
        phone: "0645.917.753",
        email: "jobs@prospect.io",
        street: "Rue des Pères Blancs 4",
        zip: 1040,
        city: "Bruxelles",
        works: "extension navigateur, vidéo, SaaS",
        techs: "Zendesk (customer support), HTML, CSS, JS, Adobe Photoshop, Ember.js, Rails, API Gmail, API Zapier",
        notes: "Formulaire de contact sur leur site"
    },
    {
        name: "iDWeaver",
        website: "https://www.idweaver.com/",
        phone: "+32 2 372 50 20",
        email: "info@idweaver.com",
        street: "Drève Richelle 159",
        zip: 1410,
        city: "Waterloo",
        works: "vitrine, corpo",
        techs: "",
        notes: ""
    },
    {
        name: "Touch",
        website: "http://www.touch-agency.net/",
        phone: "+32(0)2/373.09.69",
        email: "info@touch-agency.net",
        street: "Avenue Arnaud Fraiteur 15-23",
        zip: 1050,
        city: "Ixelles",
        works: "vitrine, corpo, UX/UI, référencement, publicité, rédaction de contenu, réseaux sociaux",
        techs: "",
        notes: ""
    },
    {
        name: "Wepika",
        website: "https://wepika.com/",
        phone: "010/280.132",
        email: "hello@wepika.com",
        street: "Rue Emile Francqui 6/3",
        zip: 1435,
        city: "Mont-Saint-Guibert",
        works: "e-commerces",
        techs: "Prestashop",
        notes: ""
    },
    {
        name: "AproPlan / Let's Build (Office)",
        website: "https://www.aproplan.com/",
        phone: "+32 2 899 97 00",
        email: "",
        street: "Chaussée de Bruxelles 135A",
        zip: 1310,
        city: "La Hulpe",
        works: "e-commerces, vitrine, corpo, mobile apps, UX/UI",
        techs: "Java, .NET, C#, Visual Studio, Git, Autodesk (Autocad, Revit, BIM 360), Navisworks, Azure, Amazon, Selenium, TypeScript, Angular.js, Angular, JS, SQL Server",
        notes: "Siège central à Bruxelles"
    },
    {
        name: "AproPlan / Let's Build (HQ)",
        website: "https://www.aproplan.com/",
        phone: "+32 2 899 97 00",
        email: "",
        street: "Avenue Louise 480",
        zip: 1050,
        city: "Bruxelles",
        works: "e-commerces, vitrine, corpo, mobile apps, UX/UI",
        techs: "Java, .NET, C#, Visual Studio, Git, Autodesk (Autocad, Revit, BIM 360), Navisworks, Azure, Amazon, Selenium, TypeScript, Angular.js, Angular, JS, SQL Server",
        notes: "IT Tower 18ième étage. Bureaux à La Hulpe"
    },
    {
        name: "Walking Men",
        website: "https://walkingmen.com",
        phone: "+32 (0) 2 412 02 52",
        email: "info@walkingmen.com",
        street: "Bloemenhofplein 12 Place du Jardin aux Fleurs",
        zip: 1000,
        city: "Bruxelles",
        works: "e-commerces, vitrine, corpo, mobile apps, UX/UI, création de contenus (photos/vidéos/textes)",
        techs: "Shopify, Prestashop, Drupal, Drupal Commerce, Magento",
        notes: ""
    },
    {
        name: "eTeamsys Belgique",
        website: "https://www.eteamsys.com/fr",
        phone: "+32 (0) 4 221 450",
        email: "info@eteamsys.com",
        street: "60 Rue du Pot d'Or",
        zip: 4000,
        city: "Liège",
        works: "digital marketing, e-commerces, corpo, emailing, mobile apps, référencement, réseaux sociaux, UI/UX",
        techs: "Drupal, Wordpress, Magento, Google AdWords, Google Analytics",
        notes: "Aussi au Luxembourg"
    },
    {
        name: "eTeamsys Luxembourg",
        website: "https://www.eteamsys.com/fr",
        phone: "+352 (0) 262 708 24",
        email: "info@eteamsys.lu",
        street: "11 Rue de l'Industrie",
        zip: 8399,
        city: "Windhof",
        works: "digital marketing, e-commerces, corpo, emailing, mobile apps, référencement, réseaux sociaux, UI/UX",
        techs: "Drupal, Wordpress, Magento, Google AdWords, Google Analytics",
        notes: "Aussi à Liège (Belgique)"
    },
    {
        name: "World of Digits Bruxelles",
        website: "https://worldofdigits.com/fr",
        phone: "",
        email: "",
        street: "112-116 Chaussée de Charleroi",
        zip: 1060,
        city: "Bruxelles",
        works: "UI/UX",
        techs: "",
        notes: "Aussi à Gand et au Luxembourg. Formulaire de contact sur le site"
    },
    {
        name: "World of Digits Gand",
        website: "https://worldofdigits.com/fr",
        phone: "",
        email: "",
        street: "Sluisweg 1 bus 15",
        zip: 9000,
        city: "Gand",
        works: "UI/UX",
        techs: "",
        notes: "Aussi à Bruxelles et au Luxembourg. Formulaire de contact sur le site"
    },
    {
        name: "World of Digits Luxembourg",
        website: "https://worldofdigits.com/fr",
        phone: "",
        email: "",
        street: "1 Rue du Fort Rheinsheim",
        zip: 2419,
        city: "Luxembourg",
        works: "UI/UX",
        techs: "",
        notes: "Aussi à Bruxelles et Gand. Formulaire de contact sur le site"
    },
    {
        name: "Deux Points",
        website: "http://deuxpoints.be",
        phone: "0497/10.66.46",
        email: "hello@deuxpoints.be",
        street: "Rue de la Plaine 9",
        zip: 6900,
        city: "Marche-En-Famenne",
        works: "Identités graphiques, logos, corpo, vitrine",
        techs: "",
        notes: ""
    },
    {
        name: "Blue Pixel Awans",
        website: "https://www.bluepixel.be",
        phone: "0497 38 70 90",
        email: "awans@bluepixel.be",
        street: "Rue de Loncin 77",
        zip: 4340,
        city: "Awans",
        works: "référencement, emailing, réseaux sociaux, logos, prints, vitrines, corpo, e-commerces, créations visuels & contenus",
        techs: "Google AdWords",
        notes: "Aussi à Sprimont"
    },
    {
        name: "Blue Pixel Sprimont",
        website: "https://www.bluepixel.be",
        phone: "04 242 90 91",
        email: "sprimont@bluepixel.be",
        street: "Rue du Suffrage Universel 1",
        zip: 4140,
        city: "Sprimont",
        works: "référencement, emailing, réseaux sociaux, logos, prints, vitrines, corpo, e-commerces, créations visuels & contenus",
        techs: "Google AdWords",
        notes: "Aussi à Awans"
    },
    {
        name: "Informex",
        website: "https://www.informex.be",
        phone: "02 705 35 00",
        email: "info@informex.be",
        street: "Avenue Jules Bordet, 168",
        zip: 1140,
        city: "Evere",
        works: "",
        techs: "Java",
        notes: "Spécialiste en informatisation du secteur automobile"
    },
    {
        name: "Graphic Plugin",
        website: "http://graphic-plugin.be",
        phone: "+32 4 223 01 76",
        email: "contact@graphic-plugin.be",
        street: "Rue Fusch, 14",
        zip: 4000,
        city: "Liège",
        works: "Logos, Chartes graphique, prints, vitrines, corpo, emailing, illustrations",
        techs: "Prezis, PowerPoint, Wordpress, Drupal, HTML5, CSS3",
        notes: ""
    },
    {
        name: "Deer Studio",
        website: "https://www.deer-studio.be",
        phone: "",
        email: "info@deer-studio.be",
        street: "Chaussée de Wavre 18A",
        zip: 4217,
        city: "Héron",
        works: "vitrine, corpo, e-commerces, logos, prints, photos, vidéos",
        techs: "Wordpress, Prestashop, Drupal, responsive design",
        notes: ""
    },
    {
        name: "Visible Creative Agency",
        website: "https://www.visible.be/fr",
        phone: "+32(0)4.341.47.17",
        email: "info@visible.be",
        street: "Troisième Avenue, 24",
        zip: 4040,
        city: "Herstal",
        works: "Identité visuelle, logos, graphismes, branding & packaging, photos, vidéos, prints, référencement, emailing, réseaux sociaux, RGPD, mobile apps",
        techs: "PHP, MySQL, ZendFramework, Google AdWords",
        notes: ""
    },
];

export default companiesList;
